# disable deployment
deploy: off
version: '{build}'
clone_depth: 1
environment:
  matrix:
    - VIM_URL: http://vim-jp.org/redirects/koron/vim-kaoriya/latest/win64/
      PYTHON: 'C:\Python35-x64'
    #- VIM_URL: http://vim-jp.org/redirects/koron/vim-kaoriya/vim73/oldest/win64/
    #- PYTHON: 'C:\Python26-x64'
install:
  - ps: |
      $zip = $Env:APPVEYOR_BUILD_FOLDER + '\vim.zip'
      $vim = $Env:APPVEYOR_BUILD_FOLDER + '\vim\'
      $redirect = Invoke-WebRequest -URI $Env:VIM_URL
      (New-Object Net.WebClient).DownloadFile($redirect.Links[0].href, $zip)
      [Reflection.Assembly]::LoadWithPartialName('System.IO.Compression.FileSystem') > $null
      [System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $vim)
      $Env:THEMIS_VIM = $vim + (Get-ChildItem $vim).Name + '\vim.exe'

  - 'git clone --depth 1 https://github.com/vim-jp/vital.vim %TEMP%\vital'
  - 'git clone --depth 1 https://github.com/thinca/vim-themis %TEMP%\vim-themis'
  - 'git clone --depth 1 --branch ver.9.2 https://github.com/Shougo/vimproc.vim %TEMP%\vimproc'
  - 'appveyor DownloadFile https://github.com/Shougo/vimproc.vim/releases/download/ver.9.2/vimproc_win64.dll -FileName %TEMP%\vimproc\lib\vimproc_win64.dll'

  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:32'
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:64'
  - 'set PATH=%PYTHON%;%PATH%'

build: off
test_script:
  - 'python --version'
  - '%THEMIS_VIM% --version'
  - '%TEMP%\vim-themis\bin\themis.bat -v'
  - '%TEMP%\vim-themis\bin\themis.bat --runtimepath %TEMP%\vimproc --runtimepath %TEMP%\vital --reporter dot'
